name: testing environments

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:  
      - name: testing 
        run: |
          echo "VERSION=1" >> $GITHUB_ENV
          echo $VERSION
      - name: echoing
        run: echo ${{ env.VERSION }}
